//! Build script: syncs the hook bridge scripts into `resources/hooks/`
//! (bundled as app resources), runs tauri_build, then scans
//! `../frontend/assets/live2d` for `*.model3.json` and emits a compile-time
//! model catalog (`$OUT_DIR/models.gen.rs`). The catalog is static — models
//! don't change at runtime — so a build-time scan avoids needing the files on
//! disk in the packaged binary (Tauri embeds frontendDist into the
//! executable).

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR set by cargo"));

    // Sync the hook bridge scripts into resources/hooks BEFORE tauri_build
    // validates the resources glob. The bundler embeds them under a plain
    // `hooks/` dir: a `../hooks/**/*` resource glob used to land in
    // `_up_\hooks\` inside the installer, so packaged builds could never
    // find the bridge and hook install failed on user machines.
    let hooks_src = manifest_dir.join("..").join("hooks");
    let hooks_dst = manifest_dir.join("resources").join("hooks");
    if let Err(e) = fs::create_dir_all(&hooks_dst) {
        println!("cargo:warning=failed to create resources/hooks: {}", e);
    }
    for name in [
        "trae-hook-bridge.ps1",
        "trae-hook-bridge.sh",
        "install-hooks.ps1",
        "hooks-template.json",
    ] {
        let s = hooks_src.join(name);
        if s.exists() {
            if let Err(e) = fs::copy(&s, hooks_dst.join(name)) {
                println!("cargo:warning=failed to copy hook resource {}: {}", name, e);
            }
        }
    }
    println!("cargo:rerun-if-changed=../hooks");

    tauri_build::build();

    // Resolve the live2d dir relative to this crate (src-tauri/).
    let live2d_dir = manifest_dir.join("..").join("frontend").join("assets").join("live2d");

    let mut models: Vec<(String, String)> = Vec::new();
    if let Ok(entries) = fs::read_dir(&live2d_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                if name.ends_with(".model3.json") {
                    let display = name.trim_end_matches(".model3.json").to_string();
                    // Webview-relative URL (frontend/ is the document root).
                    let url = format!("assets/live2d/{}", name);
                    models.push((display, url));
                }
            }
        }
    }
    models.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    let gen_path = out_dir.join("models.gen.rs");
    let mut src = String::from("/// Auto-generated by build.rs. Do not edit.\n");
    src.push_str("pub static MODELS: &[(&str, &str)] = &[\n");
    for (name, url) in &models {
        src.push_str(&format!("    ({:?}, {:?}),\n", name, url));
    }
    src.push_str("];\n");
    if let Err(e) = fs::write(&gen_path, src) {
        println!("cargo:warning=failed to write models.gen.rs: {}", e);
    }

    // Re-run if the live2d directory contents change.
    println!("cargo:rerun-if-changed=../frontend/assets/live2d");
    // Re-run when the app icon changes — without this, tauri-build's winres
    // keeps embedding the STALE cached icon into the exe (observed: two
    // repacks after `cargo tauri icon` still shipped the original icon).
    println!("cargo:rerun-if-changed=icons/icon.ico");
    // Re-run when any frontend source file changes — without this, Cargo
    // doesn't detect JS/CSS/HTML edits (no .rs files changed) and ships a
    // binary with the STALE frontend embedded via generate_context!().
    for f in ["index.html", "styles.css", "i18n.js", "tauri-bridge.js", "renderer.js", "preview.html"] {
        println!("cargo:rerun-if-changed=../frontend/{}", f);
    }
}
