//! Build script: runs tauri_build, then scans `../frontend/assets/live2d` for
//! `*.model3.json` and emits a compile-time model catalog
//! (`$OUT_DIR/models.gen.rs`). The catalog is static — models don't change at
//! runtime — so a build-time scan avoids needing the files on disk in the
//! packaged binary (Tauri embeds frontendDist into the executable).

use std::fs;
use std::path::PathBuf;

fn main() {
    tauri_build::build();

    // Resolve the live2d dir relative to this crate (src-tauri/).
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let live2d_dir = manifest_dir.join("..").join("frontend").join("assets").join("live2d");

    let mut models: Vec<(String, String)> = Vec::new();
    if let Ok(entries) = fs::read_dir(&live2d_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                if name.ends_with(".model3.json") {
                    let display = name.trim_end_matches(".model3.json").to_string();
                    // Webview-relative URL (frontend/ is the document root).
                    let url = format!("assets/live2d/{}", name);
                    models.push((display, url));
                }
            }
        }
    }
    models.sort_by(|a, b| a.0.cmp(&b.0));

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let gen_path = out_dir.join("models.gen.rs");
    let mut src = String::from("/// Auto-generated by build.rs. Do not edit.\n");
    src.push_str("pub static MODELS: &[(&str, &str)] = &[\n");
    for (name, url) in &models {
        src.push_str(&format!("    ({:?}, {:?}),\n", name, url));
    }
    src.push_str("];\n");
    if let Err(e) = fs::write(&gen_path, src) {
        println!("cargo:warning=failed to write models.gen.rs: {}", e);
    }

    // Re-run if the live2d directory contents change.
    println!("cargo:rerun-if-changed=../frontend/assets/live2d");
}
